version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    command: bash -c "npm install && npm start"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db